### PR TITLE
30 bug fixes

### LINKED ISSUE #30: Bug fixes
- Sometimes, the scroll to element doesn't work
- Loading explore page doesn't work
- give unique ids to elements

### PR DESCRIPTION
**Pull request by Rashmil-1999**
This PR fixes some known bugs and removes manual year injection. Also, add sorting in years select.

### CODE REVIEW

**Comment by navarroc** [comment]
@Rashmil-1999 Can you fix the linting issue? The build action is failing on linting.

**Comment by navarroc** [comment]
@Rashmil-1999 Is there a reason why 2023 and 2024 doesn't show in the nitrogen loss drop down for the Miller fields (crop rotation) even though we have data up until yesterday and gather it daily?

**Comment by Rashmil-1999** [comment]
Screenshot 2024-11-08 at 11 53 00 AM
For ME-02, for year 2023, we do see nitrogen data. Which field in specific are you talking about?

**Comment by navarroc** [comment]
> Screenshot 2024-11-08 at 11 53 00 AM For ME-02, for year 2023, we do see nitrogen data. Which field in specific are you talking about?

I can't check now but I think both me-03 and me-04 have 2024 data so if I manually push 2023 and 2024 I can see this year's nitrogen data.

**Comment by Rashmil-1999** [comment]
yes, you will because it might be there on geostreams but on the backend, it is not there in the fields section. Only ME-02 has a planting year of 2023. As I said on slack. The data from geostreams depends on what years of data is there for the research on our backend.

**Comment by Rashmil-1999** [comment]
The reason for this was that it won't make sense to show geostreams data for that field when there is no other data for that field for say 2024...

**Comment by navarroc** [comment]
> The reason for this was that it won't make sense to show geostreams data for that field when there is no other data for that field for say 2024...

The problem with this approach is we are getting data for some fields throughout a year and seeing the nitrogen loss and rainfall is still useful without the final yield and fertilizer data.

**Review by navarroc — APPROVED** [review]

**Pull request merged**
