### PR TITLE
34 add irrigation strategies

### LINKED ISSUE #34: Add Irrigation strategies page
We have Tuskeegee data so we can create the page for this research as well.

### PR DESCRIPTION
**Pull request by Rashmil-1999**
Renamed branch name.
- Added Irrigation strategies
- Added HOCs to handle error and loading states for fetching data.

Visit: /irrigation-strategies/:research_id

### CODE REVIEW

**Comment by navarroc** [comment]
@Rashmil-1999 For some reason, the data is off by one day. When running this locally, the soil moisture data for June 14, 2024 is reported in the graph for June 13, 2024. If you look here, I have a geostreams instance running where you can check the data for the 15 cm sensor for Tuskegee: http://direct4ag-clowder.ncsa.illinois.edu/#/explore/detail/location/z6-23134-15cm/All/

Geostreams shows the 15 cm sensor starts on July 13, 2023, but our graph says it starts July 12, 2023, which is why I think it's off. Any ideas why?

**Comment by Rashmil-1999** [comment]
Ahh good catch. I think it had something to do with the date formatting. The values and the position of the actual values were correct but the labels that were rendered suffered from some timezone errors when parsing. So depending on the time of day when you look at it, it would be right or wrong... I fixed that now.

**Comment by navarroc** [comment]
Last request and then I think we can merge this. For irrigation strategies, can you replace the "Coming soon: here will be explanations" with:

"As changing climate brings more uncertainty with regard to weather patterns, knowing how different irrigation and water management strategies performs in your area is becoming more important for optimal crop growth and yield."

That should be a reasonable placeholder until we get them to review the site.

**Comment by Rashmil-1999** [comment]
Ahh yes, so I was going to address that and the Year issue in the next PR

**Review by navarroc — APPROVED** [review]

**Pull request merged**
