### PR TITLE
16 modify landing page as per the new design

### LINKED ISSUE #16: Modify landing page as per the new design

### PR DESCRIPTION
**Pull request by Rashmil-1999**
This PR will finalize the latest Landing page design

### CODE REVIEW

**Comment by navarroc** [comment]
I can't access the figma design right now, but should the following buttons be aligned at the bottom:

1. Register a Webinar (coming soon)
2. Get Involved (in the contact us box)
3. Ask a Question (coming soon)

Other than that, I think it looks good.

**Comment by navarroc** [comment]
Finally got access to figma by finding a link to it in slack. It looks like some parts still don't align with the design. Does everything look like it matches on your screen? I'm not sure if it's screen size/resolution or if it's different on mac/linux. For example, the Ask a question should span the box and align with the text of the box end to end. For me it doesn't. Also, I don't see a "Web Tutorials" box that should be next to the Webinar's box. The contact us card at the bottom of the page isn't the same size as the participate in demonstrative plot in the design.

**Comment by Rashmil-1999** [comment]
Ahh, I see... I think I missed one and have some inconsistencies at the bottom. Let me check that

**Comment by Rashmil-1999** [comment]
This is how the Ask a Question looks on my end.... 
Screenshot 2023-11-16 at 10 25 33 PM

**Comment by Rashmil-1999** [comment]
The card behaviour is inheriting the parent which is why smaller ones resize to match the element which is due to mui's responsiveness but apart from that I don't know what you are referring to

**Comment by navarroc** [comment]
Do you get a scrollbar here?

Screenshot from 2023-11-20 14-55-04

That's the only issue of consequence that I noticed.

**Comment by Rashmil-1999** [comment]
> Do you get a scrollbar here?
> 
> Screenshot from 2023-11-20 14-55-04
> 
> That's the only issue of consequence that I noticed.

Yep, I do get the scroll bar there. The reason for that is that the card height was supposed to be fixed, but the inner content was hidden due to the text being too large. Hence, I enabled scrolling to avoid that. For me the scrollbar appears when I hover over there. Is it staying there even without hovering?

**Comment by navarroc** [comment]
> > Do you get a scrollbar here?
> > Screenshot from 2023-11-20 14-55-04
> > That's the only issue of consequence that I noticed.
> 
> Yep, I do get the scroll bar there. The reason for that is that the card height was supposed to be fixed, but the inner content was hidden due to the text being too large. Hence, I enabled scrolling to avoid that. For me the scrollbar appears when I hover over there. Is it staying there even without hovering?

It always displays. Maybe let me try to reword the text and see if I can make it more concise. Another option would be to reduce the text font a little.

**Review by navarroc — APPROVED** [review]

**Pull request merged**
