### PR TITLE
19 create drought resistant seed research display

### LINKED ISSUE #19: Create Drought Resistant Seed Research Display

### PR DESCRIPTION
**Pull request by Rashmil-1999**
This PR will add a new component that displays drought-resistant seed research. You will need to run npm install to download new libraries.... and will need latest PR of ag-services [#41](https://github.com/Direct4Ag/ag-services/pull/41)

### CODE REVIEW

**Comment by navarroc** [comment]
This looks really good just playing with it locally. I am having some trouble getting the graphs to display unless I have the developer console open. They seem to display for a moment and then are blank. I know this is a WIP so maybe you are seeing this too. Here are a few general comments, if any of these comments are too involved, we could push them back and open issues since I would like to get a version online soon. Here are two quick comments/thoughts:

1. Is it hard to show just the day of the month instead of Day 8, Day 9? Since you can see the month selected, I was thinking the Day could just be the day of the month on the x-axis (e.g. 8, 9, 10, etc). 
2. In the tooltip, could we display the full Month/Day? (e.g. June 9) instead of Day 9, Day 10?

**Comment by Rashmil-1999** [comment]
Ohh, the PR is ready for review. everything should be working normally.... could you please tell me what the issue is tomorrow in our meeting?

Yes, it is easy to change the x axis ticks and how it is displayed in the tooltip

**Comment by navarroc** [comment]
Drought is misspelled in the landing page pulldown menu. It should be Drought not Draught

**Review by navarroc — APPROVED** [review]
Runs well. It's a large PR so unless there is more to do, my suggestion is to merge this and we can tweak and review things as we get PI feedback.

**Pull request merged**
